### ISSUE TITLE
Curious

### ISSUE THREAD

**Issue by TerenceWallace** [RononDex/Simulation#1]
I'm trying to Simulate some essential human life situations and events.  For instance, I would like to simulate human birth, growth, emotional maturity, aspiration, conflict, and morality.  

However, there is no 'real' way of measuring these type of human conditions.  I'm curious if you might have any ideas on how Simulation.Core might be used to test human condition theory.

REF:
http://humancond.org/analysis/mind/interpreter_theory

**Comment by RononDex** [comment]
Sorry for the late answer. 
Yes something like that should certainly be possible.
How you would do this, is to create SimulationEngines that simulate the change in  for the human conditions. 
In my example (which simulates the solar system) you can find a simulation engine that simulates the effect of gravity on bodies. You can do something similar with humans as objects and a simulation engine that would change the conditions of the human over time.
